# Generated by Django 2.2.14 on 2023-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230624_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='best_selling',
            field=models.BooleanField(default=False, verbose_name='check this box to appear as a best selling item'),
        ),
        migrations.AddField(
            model_name='item',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='check to appear as a popular category on every page'),
        ),
    ]
